// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'searchBar': string;
  'searchBarContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
